METHOD = "METHOD"
DOT = "DOT"
LPAREN = "LPAREN"
VARIABLE = "VARIABLE"
TYPE = "TYPE"
METHOD_SELECT = "METHOD_SELECT"
MEMBER_SELECT = "MEMBER_SELECT"
EXPRESSION = "EXPRESSION"
STATEMENTS = "STATEMENTS"
METHOD_INVOCATION = "METHOD_INVOCATION"
LBRACE = "LBRACE"
NEW = "NEW"
BLOCK = "BLOCK"
BODY = "BODY"
PARAM_TYPE = "PARAMETERIZED_TYPE"
MODIFIERS = "MODIFIERS"
RETURN_TYPE = "RETURN_TYPE"
THIS = "this"
COMPILATION_UNIT = "COMPILATION_UNIT"


translate_dict = {
	"LBRACE": "{",
	"RBRACE": "}",
	"EQ": "=",
	"EQEQ": "==",
	"BANGEQ": "!=",
	"LPAREN": "(",
	"RPAREN": ")",
	"SEMI": ";",
	"COMMA": ",",
	"DOT": ".",
	"COLON": ":",
	"LT": "<",
	"GT": ">",
	"LBRACKET": "[",
	"RBRACKET": "]",
	"PLUS": "+",
	"PLUSPLUS": "++",
	"MINUS": "-",
	"MINUSMINUS": "--",
	"AMP": "&"
}